export const searchTags = [
    { title: "Front-end", slug: "front-end" },
    { title: "Back-end", slug: "back-end" },
    { title: "Full-stack", slug: "full-stack" },
    { title: "DevOps", slug: "devops" },
    { title: "Cloud", slug: "cloud" },
    { title: "Desenvolvedor", slug: "desenvolvedor" },
    { title: "Programador", slug: "programador" },
    { title: "JavaScript", slug: "javascript" },
    { title: "System", slug: "system" },
    { title: "React.js", slug: "react.js" },
    { title: "Python", slug: "python" },
    { title: "C", slug: "c" },
    { title: "Golang", slug: "golang" },
    { title: "Mobile", slug: "mobile" },
    { title: "Web", slug: "web" },
    { title: "Web3", slug: "web3" },
    { title: "Linux", slug: "linux" },
    { title: "Java", slug: "java" },
    { title: "Android", slug: "android" },
    { title: "PHP", slug: "php" },
    { title: "C#", slug: "c#" },
    { title: "C++", slug: "c++" }
]